services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pixelart\PaymentProviderDatatransBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'

    # Controllers
    Pixelart\PaymentProviderDatatrans\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Pixelart\PaymentProviderDatatransBundle\PaymentManager\Payment\Datatrans:
        arguments:
            $options: [ ]
        tags:
            -  { name: pimcore_ecommerce.payment.provider, key: 'datatrans' }

    Pixelart\PaymentProviderDatatransBundle\Datatrans\Installer:
        public: true
